export const CREATE_WINE_SUCCESS = 'CREATE_WINE_SUCCESS';
export const CREATE_WINE_FAIL = 'CREATE_WINE_FAIL';
export const LIST_WINE_SUCCESS = 'LIST_WINE_SUCCESS';
export const LIST_WINE_FAIL = 'LIST_WINE_FAIL';
export const UPDATE_WINE_SUCCESS = 'UPDATE_WINE_SUCCESS';
export const UPDATE_WINE_FAIL = 'UPDATE_WINE_FAIL';
export const REMOVE_WINE_SUCCESS = 'REMOVE_WINE_SUCCESS';
export const REMOVE_WINE_FAIL = 'REMOVE_WINE_FAIL';
